# SQL-EX with Postgres

**Курс Глеба Михайлова**  по SQL на Stepik: https://stepik.org/a/116332  

Спасибо ему за темплейт

In [1]:
# Install postgresql server
!sudo apt-get -y -qq update
!sudo apt-get -y -qq install postgresql
!sudo service postgresql start

# Setup a password `postgres` for username `postgres`
!sudo -u postgres psql -U postgres -c "ALTER USER postgres PASSWORD 'postgres';"

 * Starting PostgreSQL 12 database server
   ...done.
ALTER ROLE


In [2]:
from sqlalchemy import create_engine
con = create_engine('postgresql+psycopg2://postgres:postgres@localhost:5432/postgres')

Скачиваем данные с sql-ex

In [3]:
!wget https://sql-ex.ru/download/sql-ex-pg.sql

--2023-02-22 10:37:55--  https://sql-ex.ru/download/sql-ex-pg.sql
Resolving sql-ex.ru (sql-ex.ru)... 5.188.73.5, 2a00:ab00:1203:22:ce0:a1ff:fee0:bb42
Connecting to sql-ex.ru (sql-ex.ru)|5.188.73.5|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 41053 (40K) [application/x-sql]
Saving to: ‘sql-ex-pg.sql.1’

sql-ex-pg.sql.1     100%[===================>]  40.09K  --.-KB/s    in 0.004s  

2023-02-22 10:37:56 (9.74 MB/s) - ‘sql-ex-pg.sql.1’ saved [41053/41053]



In [4]:
with open('/content/sql-ex-pg.sql', 'r') as file:
    sql = file.read()

Запускаем скрипт

In [5]:
con.execute(sql[1:])

<ipython-input-5-5ee16aa31c9c>:1: RemovedIn20Warning: Deprecated API features detected! These feature(s) are not compatible with SQLAlchemy 2.0. To prevent incompatible upgrades prior to updating applications, ensure requirements files are pinned to "sqlalchemy<2.0". Set environment variable SQLALCHEMY_WARN_20=1 to show all deprecation warnings.  Set environment variable SQLALCHEMY_SILENCE_UBER_WARNING=1 to silence this message. (Background on SQLAlchemy 2.0 at: https://sqlalche.me/e/b8d9)
  con.execute(sql[1:])


Сделаю еще свою знаменитую функцию select, которая заворачивает пандосовкую функцию. Нужно для того, чтобы каждый раз не писать всю эту авадакедавру, а писать красивенький селект

In [6]:
import pandas as pd

In [7]:
def select(sql):
  return pd.read_sql(sql,con)

# Решения задач

**Задание: 1** Найдите номер модели, скорость и размер жесткого диска для всех ПК стоимостью менее 500 долларов. Дисплей: модель, скорость и hd

In [8]:
sql = '''
SELECT * 
FROM PC 
LIMIT 5'''
select(sql)

code model  speed  ram    hd   cd  price
0     1  1232    500   64   5.0  12x  600.0
1     2  1121    750  128  14.0  40x  850.0
2     3  1233    500   64   5.0  12x  600.0
3     4  1121    600  128  14.0  40x  850.0
4     5  1121    600  128   8.0  40x  850.0

In [9]:
sql = '''
SELECT model, 
        speed, 
        hd
FROM PC
WHERE price < 500
'''
select(sql)

model  speed    hd
0  1232    500  10.0
1  1232    450   8.0
2  1232    450  10.0
3  1260    500  10.0

**Задание: 2** Найдите производителей принтеров. Вывести: maker

In [10]:
sql = '''SELECT * 
          FROM Product 
          LIMIT 5'''
select(sql)

maker model     type
0     B  1121       PC
1     A  1232       PC
2     A  1233       PC
3     E  1260       PC
4     A  1276  Printer

In [11]:
sql = '''
SELECT DISTINCT(maker)
FROM Product
WHERE type = 'Printer'
'''
select(sql)

maker
0     A
1     D
2     E

**Задание: 3**
Найдите номер модели, объем памяти и размеры экранов ПК-блокнотов, цена которых превышает 1000 дол.

In [12]:
sql = '''
SELECT * 
FROM laptop t'''

In [13]:
select(sql)

code model  speed  ram    hd   price  screen
0     1  1298    350   32   4.0   700.0      11
1     2  1321    500   64   8.0   970.0      12
2     3  1750    750  128  12.0  1200.0      14
3     4  1298    600   64  10.0  1050.0      15
4     5  1752    750  128  10.0  1150.0      14
5     6  1298    450   64  10.0   950.0      12

Напишем сам запрос

In [14]:
sql = '''
SELECT t.model, 
       t.ram, 
       t.screen 
FROM laptop t
WHERE t.price > 1000
'''
select(sql)

model  ram  screen
0  1750  128      14
1  1298   64      15
2  1752  128      14

**Задание: 4** Найдите все записи таблицы Printer для цветных принтеров.

In [15]:
sql = '''
SELECT *
FROM Printer
WHERE color = 'y'
'''
select(sql)

code model color type  price
0     2  1433     y  Jet  270.0
1     3  1434     y  Jet  290.0

**Задание: 5** Найдите номер модели, скорость и размер жесткого диска ПК, имеющих 12x или 24x CD и цену менее 600 дол.

In [16]:
sql = '''
SELECT model,
       speed,
       hd  
FROM PC 
WHERE price < 600 AND cd IN ('12x', '24x')
'''
select(sql)

model  speed    hd
0  1232    500  10.0
1  1232    450   8.0
2  1232    450  10.0
3  1260    500  10.0

**Задание: 6** Для каждого производителя, выпускающего ПК-блокноты c объёмом жесткого диска не менее 10 Гбайт, найти скорости таких ПК-блокнотов. Вывод: производитель, скорость.

In [17]:
sql = '''
SELECT DISTINCT Product.maker, 
       Laptop.speed
FROM Product 
JOIN laptop ON Product.model = laptop .model
WHERE Laptop.hd >= 10
'''
select(sql)

maker  speed
0     A    750
1     A    450
2     A    600
3     B    750

**Задание: 7** Найдите номера моделей и цены всех имеющихся в продаже продуктов (любого типа) производителя B (латинская буква).

In [18]:
sql = '''
SELECT Laptop.model, 
       Laptop.price 
FROM Laptop 
INNER JOIN Product ON Laptop.model = Product.model
WHERE Product.maker= 'B'
UNION
SELECT PC.model, 
       PC.price 
FROM PC 
INNER JOIN Product ON PC.model = Product.model
WHERE Product.maker= 'B'
UNION
SELECT Printer.model, 
       Printer.price 
FROM Printer 
INNER JOIN Product ON Printer.model = Product.model
WHERE Product.maker= 'B'

'''
select(sql)

model   price
0  1750  1200.0
1  1121   850.0

**Задание: 8** Найдите производителя, выпускающего ПК, но не ПК-блокноты.

In [19]:
sql = '''
SELECT DISTINCT maker
FROM Product
WHERE maker NOT IN (SELECT DISTINCT maker
                    FROM Product 
                    WHERE type = 'Laptop') 
           AND type = 'PC'
'''
select(sql)

maker
0     E

**Задание: 9** Найдите производителей ПК с процессором не менее 450 Мгц. Вывести: Maker

In [20]:
sql = '''
SELECT DISTINCT pr.maker
FROM Product AS pr
RIGHT JOIN PC AS p ON pr.model = p.model
WHERE speed >= 450
'''
select(sql)

maker
0     B
1     E
2     A

**Задание: 10** Найдите модели принтеров, имеющих самую высокую цену. Вывести: model, price

In [21]:
sql = '''
SELECT model,
       price
FROM Printer
WHERE price IN (SELECT MAX(price)
                FROM Printer)
'''
select(sql)

model  price
0  1276  400.0
1  1288  400.0

**Задание:** 11 Найдите среднюю скорость ПК.

In [22]:
sql = '''
SELECT AVG(speed)
FROM PC
'''
select(sql)

avg
0  608.333333

**Задание: 12** Найдите среднюю скорость ПК-блокнотов, цена которых превышает 1000 дол.


In [23]:
sql = '''
SELECT AVG(speed)
FROM Laptop
WHERE price > 1000
'''
select(sql)


avg
0  700.0

**Задание: 13** Найдите среднюю скорость ПК, выпущенных производителем A.

In [24]:
sql = '''
SELECT AVG(speed)
FROM PC
WHERE model IN (SELECT model
                FROM Product
                WHERE maker = 'A')
'''
select(sql)

avg
0  606.25

**Задание: 14** Найдите класс, имя и страну для кораблей из таблицы Ships, имеющих не менее 10 орудий.

In [25]:
sql = '''
SELECT c.class,
       s.name,
       c.country
FROM Ships AS s
LEFT JOIN Classes AS c ON c.class = s.class
WHERE numguns >= 10
'''
select(sql)

class            name country
0       Tennessee      California     USA
1  North Carolina  North Carolina     USA
2       Tennessee       Tennessee     USA
3  North Carolina      Washington     USA
4  North Carolina    South Dakota     USA

**Задание: 15** Найдите размеры жестких дисков, совпадающих у двух и более PC. Вывести: HD

In [26]:
sql = '''
SELECT hd
FROM PC
GROUP BY hd
HAVING COUNT(hd) >= 2
'''
select(sql)

hd
0   8.0
1  20.0
2   5.0
3  14.0
4  10.0

**Задание: 16** айдите пары моделей PC, имеющих одинаковые скорость и RAM. В результате каждая пара указывается только один раз, т.е. (i,j), но не (j,i), Порядок вывода: модель с большим номером, модель с меньшим номером, скорость и RAM.


In [27]:
sql = '''
SELECT DISTINCT a.model, 
        b.model, 
        a.speed, 
        a.ram 
FROM pc a, pc b 
WHERE a.ram = b.ram 
AND a.speed = b.speed 
AND a.model > b.model
'''
select(sql)

model model  speed  ram
0  1233  1121    750  128
1  1233  1232    500   64
2  1260  1232    500   32

**Задание: 17** Найдите модели ПК-блокнотов, скорость которых меньше скорости каждого из ПК.
Вывести: type, model, speed

In [28]:
sql = '''
SELECT DISTINCT p.type,
       p.model,
       l.speed
FROM Laptop AS l
LEFT JOIN Product as p ON p.model = l.model
WHERE speed < (SELECT MIN(speed)
               FROM PC)
'''
select(sql)

type model  speed
0  Laptop  1298    350

**Задание: 18** Найдите производителей самых дешевых цветных принтеров. Вывести: maker, price

In [29]:
sql = '''
SELECT DISTINCT maker, 
       price
FROM Printer 
LEFT JOIN Product as p ON p.model = Printer.model
WHERE price = (SELECT MIN(price)
               FROM Printer
               WHERE color = 'y' )
AND color = 'y'               
 
'''
select(sql)

maker  price
0     D  270.0

**Задание: 19** Для каждого производителя, имеющего модели в таблице Laptop, найдите средний размер экрана выпускаемых им ПК-блокнотов.
Вывести: maker, средний размер экрана.

In [30]:
sql = '''
SELECT maker,
       AVG(screen)
FROM Product AS p
RIGHT JOIN Laptop ON p.model = Laptop.model
GROUP BY maker
 
'''
select(sql)

maker   avg
0     B  14.0
1     C  12.0
2     A  13.0

**Задание: 20** Найдите производителей, выпускающих по меньшей мере три различных модели ПК. Вывести: Maker, число моделей ПК.

In [31]:
sql = '''
SELECT DISTINCT p.maker, 
                COUNT(p.model)
FROM Product AS p
WHERE type = 'PC'
GROUP BY p.maker
HAVING COUNT(p.model) >= 3
'''
select(sql)

maker  count
0     E      3

**Задание: 21** Найдите максимальную цену ПК, выпускаемых каждым производителем, у которого есть модели в таблице PC.
Вывести: maker, максимальная цена.


In [32]:
sql = '''
SELECT Product.maker, 
       MAX(PC.price) 
FROM Product 
INNER JOIN PC ON Product.model = PC.model 
GROUP BY Product.maker 
'''
select(sql)

maker    max
0     B  850.0
1     E  350.0
2     A  980.0

**Задание: 22** Для каждого значения скорости ПК, превышающего 600 МГц, определите среднюю цену ПК с такой же скоростью. Вывести: speed, средняя цена.

In [33]:
sql = '''
SELECT speed, 
       AVG(price)
FROM PC
WHERE speed > 600
GROUP BY speed
'''
select(sql)

speed    avg
0    900  980.0
1    750  900.0
2    800  970.0

**Задание: 23** Найдите производителей, которые производили бы как ПК
со скоростью не менее 750 МГц, так и ПК-блокноты со скоростью не менее 750 МГц.
Вывести: Maker


In [34]:
sql = '''
SELECT DISTINCT Product.maker
FROM Product 
INNER JOIN PC ON Product.model = PC.model 
WHERE PC.speed >=750 AND
Product.maker IN (SELECT Product.maker 
                  FROM Laptop 
                  INNER JOIN Product ON Laptop.model = Product.model 
                  WHERE Laptop.speed >= 750)
GROUP BY Product.maker
'''
select(sql)

maker
0     B
1     A

**Задание: 24** Перечислите номера моделей любых типов, имеющих самую высокую цену по всей имеющейся в базе данных продукции.

In [35]:
sql = '''
SELECT model 
FROM (SELECT DISTINCT model, price 
      FROM Laptop 
      WHERE Laptop.price = (SELECT MAX(price) 
                            FROM Laptop)
UNION
SELECT DISTINCT model, 
      price FROM PC 
WHERE PC.price = (SELECT MAX(price) 
                  FROM PC)
UNION
SELECT DISTINCT model, price 
FROM Printer 
WHERE Printer.price = (SELECT MAX(price) 
                       FROM Printer)) AS t
WHERE t.price=(SELECT MAX(price) 
                FROM (SELECT DISTINCT price 
                      FROM Laptop 
                      WHERE Laptop.price = (SELECT MAX(price) 
                                            FROM Laptop)
UNION
SELECT DISTINCT price 
FROM PC 
WHERE PC.price = (SELECT MAX(price) 
                  FROM PC)
UNION
SELECT DISTINCT price 
FROM Printer 
WHERE Printer.price = (SELECT MAX(price) 
                        FROM printer)) AS t1 )
'''
select(sql)

model
0  1750

**Задание: 25** Найдите производителей принтеров, которые производят ПК с наименьшим объемом RAM и с самым быстрым процессором среди всех ПК, имеющих наименьший объем RAM. Вывести: Maker

In [36]:
sql = '''
SELECT DISTINCT p.maker
FROM Product AS p
LEFT JOIN PC ON p.model=PC.model
WHERE PC.ram IN (SELECT MIN(ram) FROM PC) 
AND PC.speed IN (SELECT MAX(speed) 
                FROM PC 
                WHERE ram = (SELECT MIN(ram) 
                            FROM PC))                     
AND p.maker IN (SELECT maker
                FROM Product
                WHERE type = 'Printer')  

'''
select(sql)

maker
0     A
1     E

**Задание: 26** Найдите среднюю цену ПК и ПК-блокнотов, выпущенных производителем A (латинская буква). Вывести: одна общая средняя цена.

In [37]:
sql = '''
SELECT AVG(price)
FROM (
  SELECT price
  FROM Product AS p
  JOIN PC ON PC.model = p.model
  WHERE maker = 'A' AND p.type = 'PC'
          UNION ALL
  SELECT price
  FROM Product AS p
  JOIN Laptop ON Laptop.model = p.model
WHERE maker = 'A' AND p.type = 'Laptop'  ) AS price       
'''
select(sql)

avg
0  754.166667

## Таблицы

In [38]:
sql = '''
SELECT *
FROM Classes 
LIMIT 5
'''
select(sql)

class type     country  numguns  bore  displacement
0        Bismarck   bb     Germany        8  15.0         42000
1            Iowa   bb         USA        9  16.0         46000
2           Kongo   bc       Japan        8  14.0         32000
3  North Carolina   bb         USA       12  16.0         37000
4          Renown   bc  Gt.Britain        6  15.0         32000

In [39]:
sql = '''
SELECT *
FROM Ships  
LIMIT 5
'''
select(sql)

name      class  launched
0  California  Tennessee      1921
1      Haruna      Kongo      1916
2        Hiei      Kongo      1914
3        Iowa       Iowa      1943
4   Kirishima      Kongo      1915

In [40]:
sql = '''
SELECT *
FROM Battles   
LIMIT 5
'''
select(sql)

name       date
0     Guadalcanal 1942-11-15
1  North Atlantic 1941-05-25
2      North Cape 1943-12-26
3  Surigao Strait 1944-10-25
4        #Cuba62a 1962-10-20

In [41]:
sql = '''
SELECT *
FROM Outcomes    
LIMIT 5
'''
select(sql)

ship          battle result
0      Bismarck  North Atlantic   sunk
1    California  Surigao Strait     OK
2  Duke of York      North Cape     OK
3          Fuso  Surigao Strait   sunk
4          Hood  North Atlantic   sunk

-------------------------------

In [42]:
sql = '''
SELECT *
FROM Product
LIMIT 5
'''
select(sql)

maker model     type
0     B  1121       PC
1     A  1232       PC
2     A  1233       PC
3     E  1260       PC
4     A  1276  Printer

In [43]:
sql = '''
SELECT *
FROM PC
LIMIT 5
'''
select(sql)

code model  speed  ram    hd   cd  price
0     1  1232    500   64   5.0  12x  600.0
1     2  1121    750  128  14.0  40x  850.0
2     3  1233    500   64   5.0  12x  600.0
3     4  1121    600  128  14.0  40x  850.0
4     5  1121    600  128   8.0  40x  850.0

In [44]:
sql = '''
SELECT *
FROM Laptop
LIMIT 5
'''
select(sql)

code model  speed  ram    hd   price  screen
0     1  1298    350   32   4.0   700.0      11
1     2  1321    500   64   8.0   970.0      12
2     3  1750    750  128  12.0  1200.0      14
3     4  1298    600   64  10.0  1050.0      15
4     5  1752    750  128  10.0  1150.0      14

In [45]:
sql = '''
SELECT *
FROM Printer
LIMIT 5
'''
select(sql)

code model color    type  price
0     1  1276     n   Laser  400.0
1     2  1433     y     Jet  270.0
2     3  1434     y     Jet  290.0
3     4  1401     n  Matrix  150.0
4     5  1408     n  Matrix  270.0